### ISSUE TITLE
Installation fails on Windows 10

### ISSUE THREAD

**Issue by soapdog** [ssbc/forked-systray#2]
There are multiple errors happening during installation on Windows 10. Mostly related to placing the helper app in the correct location. Working on it.

**Comment by soapdog** [comment]
## Bugs: 
* The executable is being named without the `.exe` extension when it is moved to the final location, windows refuse to execute it even though it passes the `testExecutable()` parrt (because it has the .exe name at that time).
* There is a typo in the `x64` arch for windows, it is written `x84`.

I am reworking these windows problems.

**Comment by soapdog** [comment]
scripts in package.json are not windows compatible...

**Comment by soapdog** [comment]
@cryptix can you test version 2.0.1 and publish it if possible?

**Comment by cryptix** [comment]
Sorry I put you threw this, @soapdog! I published with another fix as 2.0.2.
Please close this if it now works for you, ok?

ps: I'd really like your feedback on this `%ItP319xxsTLQA5sIqU4A7Fq/bi9YOgyeBPEbwNtPOsE=.sha256`

pps: the `build` step should not be needed after every install. See the above thread.

**Comment by cryptix** [comment]
should enable the same AppVeyor testing that ssbc/scuttle-shell#16 now has.
