### ISSUE TITLE
AppImage: missing shared libraries

### ISSUE THREAD

**Issue by cryptix** [ssbc/forked-systray#5]
from ssb:

> Hey, the AppImage was missing one dependency:
> `/tmp/.mount_patchblLToXr/systrayhelper: error while loading shared libraries: libdbusmenu-gtk3.so.4: cannot open shared object file: No such file or directory`
> (Adding it systemwide fixed the error)

**Comment by christianbundy** [comment]
I also had this bug when using versions of Patchbay that use scuttle-shell.
