### ISSUE TITLE
systray.onClick is not a function

### ISSUE THREAD

**Issue by sungshon** [ssbc/forked-systray#8]
i tried switching from the original package to this fork, it was not a drop in change (although the example code in the readme is the same), i'm getting:
```
TypeError: systray.onClick is not a function
    at module.exports (../src/lib/systray.js:74:13)
```

I'm a little confused about how this fork works, does it download the binary? where is it being downloaded? where does it expect it to be found after using pkg on your app?

**Comment by cryptix** [comment]
Sorry! Yes, the readme needs updating. I changed the code to using event emitters instead since it was used internally already and felt easier to extend.

A better usage example can be seen in https://github.com/ssbc/forked-systray/blob/master/test/index.test.ts

**Comment by cryptix** [comment]
I disliked having the prebuilts of the go binary inside the npm package. They are now fetched from the releases of https://github.com/ssbc/systrayhelper if the helper isn’t present in the systems `$PATH`

**Comment by sungshon** [comment]
I'm on OSX, should i presume that the file called `systrayhelper` in the module folder is the binary required for OSX? does it fetch only the required binary for the current OS (not all OS's, and skips the debugging binary?) and store it in the same folder as the module?

**Comment by sungshon** [comment]
Ok, i checked your code and it seems to indeed download only for the current OS (no debugging binary) and copy the extracted binary to the current module location.

This is good, i think i can use this for my scenario, hated having 35 mb of mostly worthless binaries in 1 module. :)

**Comment by sungshon** [comment]
I'm still uncertain what `copyDir` does in the options though, is that still used for anything?
